version: '3.8'

services:
  notifications-service:
    image: node:18-bullseye
    container_name: notifications-service
    working_dir: /usr/src/app
    command: /usr/src/app/docker/docker-run.sh
    user: '${DUID}:${DGID}'
    volumes:
      - '..:/usr/src/app:Z'
    ports:
      - '3000:3000'
    networks:
      - notifications-service-network
    env_file:
      - ./.env
    depends_on:
      - notifications-service-db
  notifications-service-db:
    image: postgres:latest
    container_name: notifications-service-db
    ports:
      - 5432:5432
    networks:
      - notifications-service-network
    env_file:
      - ./.env
    volumes:
      - notifications-service-db-data:/var/lib/postgresql/data

networks:
  notifications-service-network:
    driver: bridge

volumes:
  notifications-service-db-data: {}